###register 
POST http://127.0.0.1:2000/api/auth/register
Content-Type: application/json

{
    "username" : "member",
    "email" : "ug2424787@ines.ac.rw",
    "password" : "1234$Qwer"
}



###login 
POST http://127.0.0.1:2000/api/auth/login
Content-Type: application/json

{
    "email" : "ug2424787@ines.ac.rw",
    "password" : "1234$Qwer"
}