###create group 
POST http://127.0.0.1:2000/api/groups
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzA3MTU1OTExNCwiaWF0IjoxNzMzMDcxNTU5LCJleHAiOjE3MzM2NzYzNTl9.drP4p7DL1WXgVvaKQe9aNCogKu9pKJlWP6wKj7wkTyU

{
    "name" : "zakaria group2"
}



###update group 
PUT http://127.0.0.1:2000/api/groups/674c940e30ff9ec29b2783e0
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzA3MTU1OTExNCwiaWF0IjoxNzMzMDcxNTU5LCJleHAiOjE3MzM2NzYzNTl9.drP4p7DL1WXgVvaKQe9aNCogKu9pKJlWP6wKj7wkTyU

{
    "name" : "zakaria group,updated"
}


###delete group 
DELETE http://127.0.0.1:2000/api/groups/674c931f281ba9b47bf13ec9
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzMDcxNTg4MTM0LCJpYXQiOjE3MzMwNzE1ODgsImV4cCI6MTczMzY3NjM4OH0.pEoBu5r-H7J_ouI-kOoIbHrE6PAtf1DdSCJYq3iI6jI




###invite user 
POST http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzMDcxNTg4MTM0LCJpYXQiOjE3MzMwNzE1ODgsImV4cCI6MTczMzY3NjM4OH0.pEoBu5r-H7J_ouI-kOoIbHrE6PAtf1DdSCJYq3iI6jI

{
    "email" : "mozakk.io@gmail.com",
    "role" : "member"
}




###update role 
POST http://127.0.0.1:2000/api/groups/674e83e2875faf13e26a9939/UpdateRole
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzA3MTU1OTExNCwiaWF0IjoxNzMzMDcxNTU5LCJleHAiOjE3MzM2NzYzNTl9.drP4p7DL1WXgVvaKQe9aNCogKu9pKJlWP6wKj7wkTyU

{
    "email" : "mozakk.io@gmail.com",
    "role" : "admin"
}



###kick user 
POST http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54/kick
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzMDcxNTg4MTM0LCJpYXQiOjE3MzMwNzE1ODgsImV4cCI6MTczMzY3NjM4OH0.pEoBu5r-H7J_ouI-kOoIbHrE6PAtf1DdSCJYq3iI6jI

{
    "email" : "mozakk.io@gmail.com"
}






