###create post
POST http://127.0.0.1:2000/api/groups/674c931f281ba9b47bf13ec9/posts
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzcyMDIxNjMxMSwiaWF0IjoxNzMzNzIwMjE2LCJleHAiOjE3MzQzMjUwMTZ9.pIJ2ljDpapKgbqgBRzEc5HqIEZVzpwaoHKWDpz9zU1U

{
    "title" : "new post , by zakk",
    "content" : "new post"
}


###list posts
GET http://127.0.0.1:2000/api/groups/674c931f281ba9b47bf13ec9/posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzMyMDkyNDQxNSwiaWF0IjoxNzMzMzIwOTI0LCJleHAiOjE3MzM5MjU3MjR9.S6yKketBoPUZoy9b8W3QsWSGb6S5MNJzn8UJVeBhIJ8




###pended posts
GET http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54/posts/pended
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzQ2NDYyMDQ5OSwiaWF0IjoxNzMzNDY0NjIwLCJleHAiOjE3MzQwNjk0MjB9.rl5ZWjsNRRhM8mtrnMYYO2lZLRz-c8MJvKTL6w76NNI



###post approval
GET http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54/posts/6750617a5013f12079d9744f
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzNzIwNjQ0NjQ4LCJpYXQiOjE3MzM3MjA2NDQsImV4cCI6MTczNDMyNTQ0NH0.dtrHVP4GuJP0kJAv7bNmUOHIO_H9E2_tg1VBXp7bj3s



###update post
PUT http://127.0.0.1:2000/api/posts/6751336777ccfcaa917a1188
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmM0MjgxYmE5YjQ3YmYxM2VjMiIsInVzZXJuYW1lIjoiemFrYXJpYSIsImVtYWlsIjoibW96YWtrLmlvQGdtYWlsLmNvbSIsImNyZWF0ZV9hdCI6MTczMzMyMDkyNDQxNSwiaWF0IjoxNzMzMzIwOTI0LCJleHAiOjE3MzM5MjU3MjR9.S6yKketBoPUZoy9b8W3QsWSGb6S5MNJzn8UJVeBhIJ8

{
    "title" : "update by zakaria",
    "content" : "update by zakaria"
}



###delete post
DELETE http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54/posts/6751e0667bafe62f0f9eb4a9
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGQ0MTI1ODQ0MjJlNDJkYjc0YWJmZCIsInVzZXJuYW1lIjoibWVtYmVyIiwiZW1haWwiOiJ1ZzI0MjQ3ODdAaW5lcy5hYy5ydyIsImNyZWF0ZV9hdCI6MTczMzExNjQxMDQwMywiaWF0IjoxNzMzMTE2NDEwLCJleHAiOjE3MzM3MjEyMTB9.69H_15HYtk5sClFL3yAxzTkDqukIdVPaJMeFoxZ5vt8






###list posts
GET http://127.0.0.1:2000/api/groups/674dce6f99b7fd5cf7e72d54/user-posts
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzMDcxNTg4MTM0LCJpYXQiOjE3MzMwNzE1ODgsImV4cCI6MTczMzY3NjM4OH0.pEoBu5r-H7J_ouI-kOoIbHrE6PAtf1DdSCJYq3iI6jI





###delete pended posts
DELETE http://127.0.0.1:2000/api/groups/674c931f281ba9b47bf13ec9/posts/67568a1f4438c8ccebf64e09/delete
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NGM5MmUxMjgxYmE5YjQ3YmYxM2VjNSIsInVzZXJuYW1lIjoiYWxpIiwiZW1haWwiOiJhbGlAZ21haWwuY29tIiwiY3JlYXRlX2F0IjoxNzMzNzIwNjQ0NjQ4LCJpYXQiOjE3MzM3MjA2NDQsImV4cCI6MTczNDMyNTQ0NH0.dtrHVP4GuJP0kJAv7bNmUOHIO_H9E2_tg1VBXp7bj3s

